### ISSUE TITLE
ci token check failure

### ISSUE THREAD

**Issue by hdbikeroh** [lean-delivery/ansible-role-gitlab-runner#5]
The 'when' condition in handlers/main.yml for the 'gitlab_ci_token' fails if a token is specified

```
when:
    ...
    gitlab_ci_token | length > 0
```

resolves the problem.

**Comment by vutkin** [comment]
Hi @hdbikeroh , thanks. 
PR https://github.com/lean-delivery/ansible-role-gitlab-runner/pull/7

**Comment by vutkin** [comment]
PR merged.
